server:
  forward-headers-strategy: framework
  port: '8080'
spring:
  application:
    name: TaskListApp
  profiles:
    active: ${ENVIRONMENT_PLATFORM:dev}
task-list-app:
  http:
    auth-token: ${API_KEY:sample_key}

springdoc:
  swagger-ui:
    csrf:
      enabled: true