export const ADD_TASK = 'ADD_TASK';
export const MARK_COMPLETED = 'MARK_COMPLETED';
export const MARK_UNCOMPLETED = 'MARK_UNCOMPLETED';
export const DELETE_TASK = 'DELETE_TASK';
export const SAVE_EDIT_DESCRIPTION = 'SAVE_EDIT_DESCRIPTION';
export const ENABLE_EDIT_DESCRIPTION = 'ENABLE_EDIT_DESCRIPTION';
export const FILTER_TASK = 'FILTER_TASK';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';