name: Backend testing

on:
  push:
    branches: [ "main", "backend" ]
  pull_request:
    branches: [ "backend" ]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  test:
    name: Backend tests runner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
